# Generated by Django 4.2.1 on 2023-07-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0002_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='descriptions2',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='paragraphs2',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='titles2',
        ),
    ]
