# Generated by Django 4.2.1 on 2023-07-05 05:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0003_remove_slide_descriptions2_remove_slide_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('titles1', models.CharField(max_length=200)),
                ('descriptions1', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='welcome_section',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
