# Generated by Django 4.2.1 on 2023-07-05 06:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0004_category_filter_alter_welcome_section_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Autor', models.CharField(max_length=200)),
                ('descriptions1', tinymce.models.HTMLField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
