# Generated by Django 4.2.1 on 2023-07-05 07:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0005_books_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='features_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles1', models.CharField(max_length=200)),
                ('descriptions1', tinymce.models.HTMLField()),
            ],
        ),
    ]
