# Generated by Django 4.2.1 on 2023-07-06 07:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0006_features_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles1', models.CharField(max_length=200)),
                ('descriptions1', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='team_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name_member', models.CharField(max_length=200)),
                ('span', models.CharField(max_length=200)),
                ('descriptions1', tinymce.models.HTMLField()),
            ],
        ),
    ]
