# Generated by Django 4.2.1 on 2023-07-06 16:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0007_meet_staff_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles1', models.CharField(max_length=200)),
                ('span', models.CharField(max_length=200)),
                ('descriptions1', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_homeimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles1', models.CharField(max_length=200)),
                ('span', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('lacation', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('descriptions1', tinymce.models.HTMLField()),
                ('descriptions2', tinymce.models.HTMLField()),
            ],
        ),
    ]
