# Generated by Django 4.2.1 on 2023-07-06 18:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0008_event_home_event_homeimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='booksmediagirdviewv2_Page_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles1', models.CharField(max_length=200)),
                ('span', models.CharField(max_length=200)),
                ('descriptions1', tinymce.models.HTMLField()),
                ('list1', models.CharField(max_length=50)),
            ],
        ),
    ]
