# Generated by Django 4.2.1 on 2023-07-08 07:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0011_bookmgv2'),
    ]

    operations = [
        migrations.CreateModel(
            name='booksmgv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles1', models.CharField(max_length=200)),
                ('Autor', models.CharField(max_length=200)),
                ('descriptions1', tinymce.models.HTMLField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
