# Generated by Django 4.2.1 on 2023-07-09 14:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0012_booksmgv2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('titles1', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('lacation', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('descriptions1', tinymce.models.HTMLField()),
            ],
        ),
    ]
