# Generated by Django 4.2.1 on 2023-07-09 15:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0013_event_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloge_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('titles1', models.CharField(max_length=200)),
                ('titles11', models.CharField(max_length=200)),
                ('titles2', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=50)),
                ('descriptions1', tinymce.models.HTMLField()),
            ],
        ),
    ]
