# Generated by Django 4.2.1 on 2023-07-14 06:49

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0020_bloge_remove_bloge_list_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('lacation', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('descriptions1', tinymce.models.HTMLField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campany.image_category')),
            ],
        ),
        migrations.CreateModel(
            name='Event_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campany.event_list')),
            ],
        ),
    ]
