# Generated by Django 4.2.1 on 2023-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0022_alter_image_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='recent_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('titlee', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
