# Generated by Django 4.2.1 on 2023-07-15 19:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0026_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('audio_book', models.FileField(blank=True, null=True, upload_to='audio_books')),
                ('descriptions1', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
