# Generated by Django 4.2.1 on 2023-07-16 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0030_audiobook_title2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=50)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/')),
                ('title', models.CharField(max_length=200)),
                ('days', models.IntegerField(verbose_name='Number of days')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='EventHomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('span', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('lacation', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='event-images/')),
            ],
        ),
        migrations.CreateModel(
            name='MeetStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='category',
            new_name='BookCategory',
        ),
        migrations.RenameModel(
            old_name='books_home',
            new_name='BookHome',
        ),
        migrations.RenameModel(
            old_name='Category_Filter',
            new_name='CategoryFilter',
        ),
        migrations.RenameModel(
            old_name='Event_list',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Event_home',
            new_name='EventHome',
        ),
        migrations.RenameModel(
            old_name='Event_news',
            new_name='EventNews',
        ),
        migrations.RenameModel(
            old_name='Meet_Staff',
            new_name='FeatureHome',
        ),
        migrations.RenameModel(
            old_name='image_category',
            new_name='ImageCategory',
        ),
        migrations.RenameModel(
            old_name='team_member',
            new_name='TeamMember',
        ),
        migrations.RenameModel(
            old_name='Welcome_Section',
            new_name='WelcomeSection',
        ),
        migrations.DeleteModel(
            name='Bk',
        ),
        migrations.RemoveField(
            model_name='bkmv2_allcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='bloge',
        ),
        migrations.DeleteModel(
            name='bloge_list',
        ),
        migrations.RemoveField(
            model_name='bookks',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookks',
            name='category',
        ),
        migrations.DeleteModel(
            name='bookmgv2',
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.DeleteModel(
            name='booksmediagirdviewv2_Page_Banner',
        ),
        migrations.DeleteModel(
            name='booksmgv2',
        ),
        migrations.DeleteModel(
            name='contactaddress',
        ),
        migrations.RemoveField(
            model_name='event_detail',
            name='Event_list',
        ),
        migrations.DeleteModel(
            name='Event_homeimages',
        ),
        migrations.DeleteModel(
            name='features_home',
        ),
        migrations.DeleteModel(
            name='recent_news',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='slides',
        ),
        migrations.RenameField(
            model_name='bookhome',
            old_name='descriptions1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='categoryfilter',
            old_name='descriptions1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='categoryfilter',
            old_name='titles1',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='titles1',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='descriptions1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='titles1',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='eventhome',
            old_name='descriptions1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='eventhome',
            old_name='titles1',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='eventnews',
            old_name='descriptions1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='featurehome',
            old_name='descriptions1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='featurehome',
            old_name='titles1',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='titles1',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='descriptions1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='paragraphs1',
            new_name='paragraph',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='titles1',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='descriptions1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='description',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='title',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='audio_book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='inventory',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Campany.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=tinymce.models.HTMLField(default='sdfghj'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 16, 17, 50, 131854, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='bkmv2_AllCategory',
        ),
        migrations.DeleteModel(
            name='Bookks',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Event_detail',
        ),
    ]
