# Generated by Django 4.2.1 on 2023-07-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0032_subscriber_alter_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='teams/'),
        ),
    ]
