# Generated by Django 4.2.1 on 2023-07-16 18:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0033_alter_teammember_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('span', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('list1', models.CharField(max_length=50)),
            ],
        ),
    ]
