# Generated by Django 4.2.1 on 2023-07-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0035_event_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='lacation',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/'),
        ),
    ]
