# Generated by Django 4.2.1 on 2023-07-17 16:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0036_rename_lacation_event_location_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/')),
                ('title', models.CharField(max_length=200)),
                ('days', models.IntegerField(verbose_name='Number of days')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
