# Generated by Django 4.2.1 on 2023-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0039_eventpostimage_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Audio/'),
        ),
    ]
