# Generated by Django 4.2.1 on 2023-07-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0040_audiobook_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBookS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Audio/')),
                ('audio_file', models.FileField(upload_to='audiobooks/')),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campany.book')),
            ],
        ),
    ]
