# Generated by Django 4.2.1 on 2023-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0041_audiobooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
