# Generated by Django 4.2.1 on 2023-07-25 07:22

from django.db import migrations, models
import phonenumber_field.modelfields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0043_fact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('address', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
