# Generated by Django 4.2.1 on 2024-06-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0044_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='quantities',
            field=models.IntegerField(default=0),
        ),
    ]
