# Generated by Django 4.2.1 on 2024-06-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0045_book_number_sold_book_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantities',
        ),
    ]
