# Generated by Django 4.2.1 on 2024-06-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0047_bankinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
