# Generated by Django 4.2.1 on 2024-06-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0048_pdfdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
