# Generated by Django 4.2.1 on 2024-06-28 14:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0049_pdfdocument_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walia_Published_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('description', tinymce.models.HTMLField()),
                ('publish_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('number_sold', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campany.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campany.bookcategory')),
            ],
        ),
    ]
