# Generated by Django 4.2.1 on 2024-06-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0050_walia_published_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consign_date', models.DateField()),
                ('delivered_to', models.CharField(max_length=255)),
                ('delivered_by', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('book_title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consignee_signature', models.CharField(max_length=255)),
                ('consigner_signature', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campany.bookcategory')),
            ],
        ),
    ]
