# Generated by Django 4.2.1 on 2024-06-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0051_consignmentagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentagreement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ConsignmentAgreements/'),
        ),
    ]
