# Generated by Django 4.2.1 on 2024-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0053_remove_consignmentagreement_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentagreement',
            name='contractual_obligation',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consignmentagreement',
            name='copyright_infringement_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consignmentagreement',
            name='nda_request_effective',
            field=models.BooleanField(default=False),
        ),
    ]
