# Generated by Django 4.2.1 on 2024-06-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0054_consignmentagreement_contractual_obligation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentagreement',
            name='national_id',
            field=models.ImageField(blank=True, null=True, upload_to='national id/'),
        ),
    ]
