# Generated by Django 4.2.1 on 2024-06-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0055_consignmentagreement_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentagreement',
            name='consign_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
