# Generated by Django 4.2.1 on 2024-07-02 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0056_alter_consignmentagreement_consign_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Amharic', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Campany.booklanguage'),
        ),
        migrations.AddField(
            model_name='consignmentagreement',
            name='Language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Campany.booklanguage'),
        ),
        migrations.AddField(
            model_name='walia_published_book',
            name='Language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Campany.booklanguage'),
        ),
    ]
