# Generated by Django 4.2.1 on 2024-07-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0057_booklanguage_book_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentagreement',
            name='Language',
        ),
    ]
