# Generated by Django 4.2.1 on 2024-07-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0058_remove_consignmentagreement_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='walia_published_book',
            name='Language',
        ),
        migrations.DeleteModel(
            name='BookLanguage',
        ),
    ]
