# Generated by Django 4.2.1 on 2024-07-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0060_alter_consignmentagreement_national_id_ebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentagreement',
            name='national_id',
        ),
    ]
