# Generated by Django 4.2.1 on 2024-07-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0063_remove_book_language_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsignmentAgreement',
        ),
    ]
