# Generated by Django 4.2.1 on 2024-07-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0064_delete_consignmentagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consign_date', models.DateTimeField(auto_now=True)),
                ('delivered_to', models.CharField(max_length=255)),
                ('delivered_by', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ConsignmentAgreements/')),
                ('book_title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('national_id', models.ImageField(blank=True, null=True, upload_to='national_id/')),
                ('consignee_signature', models.CharField(max_length=255)),
                ('consigner_signature', models.CharField(max_length=255)),
                ('contractual_obligation', models.TextField()),
                ('nda_request_effective', models.BooleanField(default=False)),
                ('copyright_infringement_claim', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campany.bookcategory')),
            ],
        ),
    ]
