# Generated by Django 4.2.1 on 2024-07-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0066_booklanguage_book_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='language',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='consignmentagreement',
            old_name='language',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='walia_published_book',
            old_name='language',
            new_name='Language',
        ),
    ]
