# Generated by Django 4.2.1 on 2024-07-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0067_rename_language_book_language_and_more'),
    ]

    operations = [
    ]
