# Generated by Django 4.2.1 on 2024-07-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0068_auto_20240709_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walia_published_book',
            name='Language',
        ),
    ]
