# Generated by Django 4.2.1 on 2024-07-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0069_remove_walia_published_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='consignmentagreement',
            name='Language',
        ),
        migrations.DeleteModel(
            name='BookLanguage',
        ),
    ]
