# Generated by Django 4.2.1 on 2024-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0070_remove_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ebook/'),
        ),
    ]
