# Generated by Django 4.2.1 on 2024-07-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0074_booklanaguage_book_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audiobooks',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
