# Generated by Django 4.2.1 on 2024-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0076_ebook_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
