# Generated by Django 4.2.1 on 2024-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0077_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='company_images/')),
            ],
        ),
    ]
