# Generated by Django 4.2.1 on 2024-07-18 07:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0078_companyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=tinymce.models.HTMLField(max_length=9000),
        ),
    ]
