# Generated by Django 4.2.1 on 2024-07-20 04:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0079_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='welcome/')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('paragraph', tinymce.models.HTMLField()),
            ],
        ),
    ]
