# Generated by Django 4.2.1 on 2024-07-25 07:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0080_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('number_of_books', models.IntegerField()),
            ],
        ),
    ]
