# Generated by Django 4.2.1 on 2024-07-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0082_alter_customer_information_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_information',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Campany.book'),
            preserve_default=False,
        ),
    ]
