# Generated by Django 4.2.1 on 2024-07-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0083_customer_information_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_information',
            name='book',
        ),
    ]
