# Generated by Django 4.2.1 on 2024-07-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0086_remove_service_link_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
