# Generated by Django 4.2.1 on 2024-08-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0087_companyinfo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTextBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ebook/')),
                ('file', models.FileField(upload_to='ebooks/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campany.book')),
            ],
        ),
    ]
