# Generated by Django 4.2.1 on 2024-08-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campany', '0088_audiotextbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_information',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Campany.book'),
        ),
    ]
